# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cameron Doyle
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://camerondoyle.co.uk"

author:
    firstname: Cameron
    surname: Doyle
    fullname: Cameron Doyle
    email: hello@camerondoyle.co.uk
    twitter: CameronD17
    github: CameronD17
    facebook: cameron.doyle
    linkedin: camerond17
    instagram: camerond17
    stackoverflow: 1669993/camerond17
    
description: > # this means to ignore newlines until "baseurl:"
  Personal portfolio website of Cameron Doyle, a programmer 
  and software engineer based in Edinburgh, Scotland.

# Build settings
markdown: kramdown
